ALTER TABLE debts
    ADD COLUMN IF NOT EXISTS color_key VARCHAR(32) NOT NULL DEFAULT 'wine';

ALTER TABLE debts
    ADD COLUMN IF NOT EXISTS initial_amount DOUBLE PRECISION;

ALTER TABLE debts
    ADD COLUMN IF NOT EXISTS last_offer_discount_percent DOUBLE PRECISION;
